apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: one
  name: appone
spec:
  replicas: 3
  selector:
    matchLabels:
      app: one
  template:
    metadata:
      labels:
        app: one
    spec:
      containers:
      - name: container-0
        image: dsosedovpvtl/appone@
