apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: appone
  labels:
    apps.tanzu.vmware.com/workload-type: web
    apps.tanzu.vmware.com/has-tests: "false"
    app.kubernetes.io/part-of: appone
    tanzu.app.live.view: "true"
    tanzu.app.live.view.application.flavours: spring
    tanzu.app.live.view.application.name: appone
spec:
  source:
    git:
      url: https://github.com/dsosedov-vmw/supplychain-apps.git
      ref:
        branch: main
    subPath: appone
