#@ load("@ytt:data", "data")

apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: appone
  labels:
    networking.knative.dev/visibility: cluster-local
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
    spec:
      #! imagePullSecrets:
      #! - name: registry-credentials
      #! - name: tap-registry
      containers:
      - image: dsosedovpvtl/appone@
        ports:
        - containerPort: 8080
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault
